# https://docs.nats.io/running-a-nats-service/configuration
# Example NATS configuration
listen: 127.0.0.1:4222
# Monitoring
http: 127.0.0.1:8222
# JetStream
jetstream {
  store_dir: /tmp/jetstream
  max_mem: 1G
  max_file: 100G
}
# Auth
authorization {
  token: "secret"
}
# Logging
debug:   false
trace:   true
logtime: false
logfile_size_limit: 1GB
logfile_max_num: 100
log_file: "/tmp/nats-server.log"
